# Generated by Django 4.1.7 on 2023-03-27 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('features', '0002_remove_question_quiz_delete_choice_delete_question_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalizedLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('language_level', models.CharField(max_length=50)),
                ('interests', models.CharField(max_length=200)),
                ('learning_goals', models.TextField()),
            ],
        ),
    ]
