# Generated by Django 4.1.7 on 2023-04-06 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0005_interest_lesson_delete_personalizedlesson'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario', models.CharField(max_length=100)),
                ('difficulty', models.CharField(max_length=100)),
                ('conversation', models.TextField()),
            ],
        ),
    ]
