# Generated by Django 4.1.7 on 2023-04-06 02:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0006_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='time_generated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
