# Generated by Django 4.1.7 on 2023-03-15 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lectures", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Quiz",
            new_name="Exercise",
        ),
    ]
