# Generated by Django 4.1.7 on 2023-03-15 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("lectures", "0002_rename_quiz_exercise"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("chinese_characters", models.CharField(max_length=255)),
                (
                    "audio_clip",
                    models.FileField(
                        blank=True, null=True, upload_to="readings/audio_clips"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="userlessonprogress",
            name="lesson",
        ),
        migrations.RemoveField(
            model_name="userlessonprogress",
            name="user",
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="image",
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="video_url",
        ),
        migrations.DeleteModel(
            name="Exercise",
        ),
        migrations.DeleteModel(
            name="UserLessonProgress",
        ),
        migrations.AddField(
            model_name="reading",
            name="lesson",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="lectures.lesson"
            ),
        ),
    ]
