# Generated by Django 4.1.7 on 2023-03-15 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("lectures", "0003_reading_remove_userlessonprogress_lesson_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Listening",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phrase", models.CharField(max_length=100)),
                ("hanzi", models.CharField(max_length=100)),
                ("yingzi", models.CharField(max_length=100)),
                (
                    "audio_clip",
                    models.FileField(
                        blank=True, null=True, upload_to="listening/audio_clips"
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lectures.lesson",
                    ),
                ),
            ],
        ),
    ]
