# Generated by Django 4.1.7 on 2023-03-24 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0007_character_delete_writing'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='char_image',
            field=models.ImageField(null=True, upload_to='characters'),
        ),
    ]
