# Generated by Django 4.1.7 on 2023-03-24 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0008_character_char_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='char_image',
            new_name='svg_image',
        ),
    ]
