# Generated by Django 4.1.7 on 2023-03-24 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0005_listening_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Writing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hanzi', models.CharField(max_length=5)),
                ('pinyin', models.CharField(max_length=5)),
                ('character_svg', models.ImageField(upload_to='characters')),
            ],
        ),
        migrations.RemoveField(
            model_name='listening',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='reading',
            name='lesson',
        ),
    ]
