# Generated by Django 4.1.7 on 2023-03-24 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0012_remove_character_svg_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('video', models.FileField(upload_to='video_lessons')),
                ('posted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Character',
        ),
    ]
