# Generated by Django 4.1.7 on 2023-04-05 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lessonprogress',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='lessonprogress',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='lessonprogress',
            name='user',
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
        migrations.DeleteModel(
            name='LessonProgress',
        ),
    ]
